// app/layout.tsx
import React from 'react'
import '../styles/globals.css'
import "@fontsource/poppins/400.css"
import "@fontsource/poppins/600.css"
import "@fontsource/poppins/700.css"
import "@fontsource/merriweather/400.css"
import "@fontsource/merriweather/700.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='font-sans'>{children}</body>
    </html>
  )
}
